#!/bin/bash

heroku pg:reset DATABASE --confirm sheltered-beach-44318
heroku pg:psql -a sheltered-beach-44318 <db/structure2.sql
heroku pg:psql << EOF
\copy experimentinfo FROM 'db/s2/s2_info.csv' DELIMITER ',' CSV;
\copy info FROM 'db/s2/compoundInfoNew2.csv' DELIMITER ',' CSV;
\copy NLS FROM 'db/s2/S2_nls.csv' DELIMITER ',' CSV;
\copy sytoxgreen FROM 'db/s2/S2_sg.csv' DELIMITER ',' CSV;
\copy confluency FROM 'db/s2/S2_con.csv' DELIMITER ',' CSV;
\copy experimentInfo FROM 'db/exp2/expInfo2.csv' DELIMITER ',' CSV;
\copy NLS FROM 'db/exp2/NLSInfoNew2.csv' DELIMITER ',' CSV;
\copy sytoxgreen FROM 'db/exp2/sytoxInfoNew2.csv' DELIMITER ',' CSV;
\copy confluency FROM 'db/exp2/confluenceInfoNew2.csv' DELIMITER ',' CSV;
\copy experimentInfo FROM 'db/s4/s4_info.csv' DELIMITER ',' CSV;
\copy NLS FROM 'db/s4/S4_nls.csv' DELIMITER ',' CSV;
\copy sytoxgreen FROM 'db/s4/S4_sg.csv' DELIMITER ',' CSV;
\copy confluency FROM 'db/s4/S4_con.csv' DELIMITER ',' CSV;
\dt
EOF
